version: "3.8"
services:
  laterbot:
    image: laterbot:latest
    build: .
    container_name: laterbot
    volumes:
      # Host sqlite file bind-mounted into container /data so it can be swapped externally
      - type: bind
        source: ./data/
        target: /data/
    environment:
      # Environment vars are private and should be instead specified via cli or in `docker-compose-localtest.yml`
